KeyError                                  Traceback (most recent call last)
File /opt/ailabs/aire/envs/aire-jupyter/lib/python3.9/site-packages/pandas/core/indexes/base.py:3802, in Index.get_loc(self, key, method, tolerance)
   3801 try:
-> 3802     return self._engine.get_loc(casted_key)
   3803 except KeyError as err:

File /opt/ailabs/aire/envs/aire-jupyter/lib/python3.9/site-packages/pandas/_libs/index.pyx:138, in pandas._libs.index.IndexEngine.get_loc()

File /opt/ailabs/aire/envs/aire-jupyter/lib/python3.9/site-packages/pandas/_libs/index.pyx:165, in pandas._libs.index.IndexEngine.get_loc()

File pandas/_libs/hashtable_class_helper.pxi:5745, in pandas._libs.hashtable.PyObjectHashTable.get_item()

File pandas/_libs/hashtable_class_helper.pxi:5753, in pandas._libs.hashtable.PyObjectHashTable.get_item()

KeyError: 'ObligorId'

The above exception was the direct cause of the following exception:

KeyError                                  Traceback (most recent call last)
Cell In[129], line 52
     47 overall_economic_impact_sum += overall_economic_impact
     49 # Create a DataFrame for the current counterparty
     50 cp_df = pd.DataFrame({
     51     'Counterparty Name': [counterparty],
---> 52     'ObligorId': cp_data['ObligorId'].iloc[0],  # Extract ObligorId for the counterparty
     53     'Vd': [vd],
     54     'Vd+1': [vd_plus_1],
     55     'Vd+2': [vd_plus_2],
     56     'Vd+3': [vd_plus_3],
     57     'Vd+4': [vd_plus_4],
     58     'Vd+5': [vd_plus_5],
     59     'Vd+7': [vd_plus_7],
     60     'Vd>7': [vd_gt_7],
     61     'Total Fails': [total_fails],
     62     'Overall Economic Impact': [overall_economic_impact]
     63 })
     65 # Append the DataFrame to the list
     66 dfs.append(cp_df)

File /opt/ailabs/aire/envs/aire-jupyter/lib/python3.9/site-packages/pandas/core/frame.py:3807, in DataFrame.__getitem__(self, key)
   3805 if self.columns.nlevels > 1:
   3806     return self._getitem_multilevel(key)
-> 3807 indexer = self.columns.get_loc(key)
   3808 if is_integer(indexer):
   3809     indexer = [indexer]

File /opt/ailabs/aire/envs/aire-jupyter/lib/python3.9/site-packages/pandas/core/indexes/base.py:3804, in Index.get_loc(self, key, method, tolerance)
   3802     return self._engine.get_loc(casted_key)
   3803 except KeyError as err:
-> 3804     raise KeyError(key) from err
   3805 except TypeError:
   3806     # If we have a listlike key, _check_indexing_error will raise
   3807     #  InvalidIndexError. Otherwise we fall through and re-raise
   3808     #  the TypeError.
   3809     self._check_indexing_error(key)

KeyError: 'ObligorId'
