ValueError                                Traceback (most recent call last)
Cell In[158], line 96
     94 for column in ['Vd', 'Vd+1', 'Vd+2', 'Vd+3', 'Vd+4', 'Vd+5', 'Vd+7', 'Vd>7']:
     95     for row in range(2, len(new_excel_df) + 2):  # Start from row 2 (excluding header)
---> 96         cell = ws[f"{column}{row}"]
     97         if cell.value is not None and cell.value != '-' and cell.value > 0:
     98             cell.fill = condition_fill

File /opt/ailabs/aire/envs/aire-jupyter/lib/python3.9/site-packages/openpyxl/worksheet/worksheet.py:290, in Worksheet.__getitem__(self, key)
    287 if isinstance(key, int):
    288     key = str(key
    289               )
--> 290 min_col, min_row, max_col, max_row = range_boundaries(key)
    292 if not any([min_col, min_row, max_col, max_row]):
    293     raise IndexError("{0} is not a valid coordinate or range".format(key))

File /opt/ailabs/aire/envs/aire-jupyter/lib/python3.9/site-packages/openpyxl/utils/cell.py:135, in openpyxl.utils.cell.range_boundaries()

ValueError: Vd+12 is not a valid coordinate or range
