KeyError                                  Traceback (most recent call last)
Cell In[63], line 42
     39 output_df.rename(columns={'ObligorId': 'ObligorId', 'CashScore': 'CashScore'}, inplace=True)
     41 # Set 'ObligorId' before 'Counterparty Name'
---> 42 output_df = output_df[['ObligorId', 'Counterparty Name', 'Operation Type', 'Trade Date', 'Trade Price', 'Value Date', 'Primary Original Quantity', 'Settlement Instrument Name', 'ISIN Primary Instrument Reference', 'Primary Instrument Long Name', 'SMO Trade Reference', 'Internal Status Narrative', 'Sales Person Name', 'CBBT_PX_ASK', 'Economic Impact', 'LQA (Liq Score)', 'Days Elapsed', 'CashScore']]
     44 output_filename = 'output.xlsx'
     45 output_df.to_excel(output_filename, index=False, sheet_name='Sheet1')

File /opt/ailabs/aire/envs/aire-jupyter/lib/python3.9/site-packages/pandas/core/frame.py:3813, in DataFrame.__getitem__(self, key)
   3811     if is_iterator(key):
   3812         key = list(key)
-> 3813     indexer = self.columns._get_indexer_strict(key, "columns")[1]
   3815 # take() does not accept boolean indexers
   3816 if getattr(indexer, "dtype", None) == bool:

File /opt/ailabs/aire/envs/aire-jupyter/lib/python3.9/site-packages/pandas/core/indexes/base.py:6070, in Index._get_indexer_strict(self, key, axis_name)
   6067 else:
   6068     keyarr, indexer, new_indexer = self._reindex_non_unique(keyarr)
-> 6070 self._raise_if_missing(keyarr, indexer, axis_name)
   6072 keyarr = self.take(indexer)
   6073 if isinstance(key, Index):
   6074     # GH 42790 - Preserve name from an Index

File /opt/ailabs/aire/envs/aire-jupyter/lib/python3.9/site-packages/pandas/core/indexes/base.py:6133, in Index._raise_if_missing(self, key, indexer, axis_name)
   6130     raise KeyError(f"None of [{key}] are in the [{axis_name}]")
   6132 not_found = list(ensure_index(key)[missing_mask.nonzero()[0]].unique())
-> 6133 raise KeyError(f"{not_found} not in index")

KeyError: "['ObligorId', 'CashScore'] not in index"
